# Generated by Django 5.1.1 on 2024-09-14 20:36

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                blank=True,
                error_messages={"unique": "이미 nickname이 존재합니다."},
                help_text="문자, 숫자, 특수문자( @/./+/-/_ )를 이용해 닉네임을 만들어주세요.",
                max_length=100,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="nickname",
            ),
        ),
    ]
