# Generated by Django 5.1.1 on 2024-09-13 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("account_number", models.CharField(max_length=20, verbose_name="계좌번호")),
                (
                    "bank_code",
                    models.CharField(
                        choices=[
                            ("088", "신한은행"),
                            ("002", "산업은행"),
                            ("003", "기업은행"),
                            ("004", "국민은행"),
                            ("005", "외환은행"),
                        ],
                        max_length=10,
                        verbose_name="은행코드",
                    ),
                ),
                ("account_type", models.CharField(max_length=20, verbose_name="계좌종류")),
                ("balance", models.PositiveIntegerField(verbose_name="잔액")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="계좌주"
                    ),
                ),
            ],
        ),
    ]
