# Generated by Django 5.1.1 on 2024-09-14 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("transaction_amount", models.PositiveIntegerField()),
                ("transaction_balance", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "transaction_type",
                    models.CharField(choices=[("deposit", "Deposit"), ("withdrawal", "Withdrawal")], max_length=20),
                ),
                (
                    "payment_method",
                    models.CharField(choices=[("Bank", "Bank"), ("Automatic", "Automatic")], max_length=20),
                ),
                ("transaction_description", models.CharField(blank=True, max_length=255)),
                ("transaction_datetime", models.DateTimeField(auto_now_add=True)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="accounts.account")),
            ],
        ),
    ]
