# Generated by Django 5.1.1 on 2024-09-18 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transaction_historys", "0002_transactionhistory_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactionhistory",
            name="transaction_datetime",
        ),
    ]
