# Generated by Django 5.1.1 on 2024-09-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction_historys", "0003_remove_transactionhistory_transaction_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionhistory",
            name="transaction_balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
